import { PassportData } from '../types/passport';

export const SAMPLE_PASSPORTS: PassportData[] = [
  {
    id: 'sample-yem-1',
    documentType: 'P',
    documentSubtype: '<',
    issuingState: 'YEM',
    surname: 'AL-ZAHEAH',
    surnameAr: 'الزحيه',
    givenNames: 'MOHAMMED SHAWQI MOHAMMED HASAN',
    givenNamesAr: 'محمد شوقي محمد حسن',
    passportNumber: '13966269',
    nationality: 'YEM',
    birthDate: '2004-02-02',
    sex: 'M',
    expiryDate: '2030-04-17',
    issueDate: '2024-04-17',
    personalNumber: '1002030405',
    profession: 'LABORER',
    professionAr: 'عامل',
    placeOfBirth: 'ALMAHWEET - YEM',
    placeOfBirthAr: 'اليمن - المحويت',
    issuingAuthority: 'KHAWKHAH',
    issuingAuthorityAr: 'الخوخة'
  },
  {
    id: 'sample-sau-1',
    documentType: 'P',
    documentSubtype: '<',
    issuingState: 'SAU',
    surname: 'AL-GHAMDI',
    surnameAr: 'الغامدي',
    givenNames: 'ABDULLAH FAHAD SALEH',
    givenNamesAr: 'عبدالله فهد صالح',
    passportNumber: 'G14704563',
    nationality: 'SAU',
    birthDate: '1995-08-14',
    sex: 'M',
    expiryDate: '2034-01-10',
    issueDate: '2024-01-10',
    personalNumber: '1098765432',
    profession: 'SOFTWARE ENGINEER',
    professionAr: 'مهندس برمجيات',
    placeOfBirth: 'RIYADH - SAU',
    placeOfBirthAr: 'المملكة العربية السعودية - الرياض',
    issuingAuthority: 'RIYADH',
    issuingAuthorityAr: 'جوازات منطقة الرياض'
  },
  {
    id: 'sample-egy-1',
    documentType: 'P',
    documentSubtype: '<',
    issuingState: 'EGY',
    surname: 'EL-MASRI',
    surnameAr: 'المصري',
    givenNames: 'NOUR AHMED MAHMOUD',
    givenNamesAr: 'نور أحمد محمود',
    passportNumber: 'A28941033',
    nationality: 'EGY',
    birthDate: '1998-11-20',
    sex: 'F',
    expiryDate: '2031-06-05',
    issueDate: '2024-06-05',
    personalNumber: '29811200102345',
    profession: 'PHYSICIAN',
    professionAr: 'طبيبة بشري',
    placeOfBirth: 'CAIRO - EGY',
    placeOfBirthAr: 'مصر - القاهرة',
    issuingAuthority: 'CAIRO',
    issuingAuthorityAr: 'مصلحة الجوازات والهجرة'
  }
];
